### ISSUE TITLE
SyntaxError: invalid regexp group using v1.3*

### ISSUE THREAD

**Issue by WesleyGoncalves** [imyelo/docsify-plantuml#11]
I am  getting this error when using versions `1.3.*` and the image is not getting rendered by the plantUML server - I tried using local and remote servers.

`SyntaxError: invalid regexp group              docsify-plantuml.min.js:1:7`

My markdown file is the sample in the [README](https://github.com/imyelo/docsify-plantuml#usage) file:

```md
### Section X
```plantuml
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```

I tried including this plugin using these URLs

```
//unpkg.com/docsify-plantuml/dist/docsify-plantuml.min.js
//unpkg.com/docsify-plantuml@1.3.1/dist/docsify-plantuml.min.js
//unpkg.com/docsify-plantuml@1.3.0/dist/docsify-plantuml.min.js
```

 With the version `1.2.2`, it works

```
//unpkg.com/docsify-plantuml@1.2.2/dist/docsify-plantuml.min.js
```

More information:

- Version 1.3.1 | 1.3.0
- Docsify-cli 4.4.0
 - Node 14.2.0
- Ubuntu 20.04
- Firefox 76.0.1 (64-bit)

**Comment by imyelo** [comment]
related to #9
seems like the regexp is incompatible with firefox.

**Comment by imyelo** [comment]
This minimal use cases produce the same error: 
https://regex101.com/r/hNXNiW/1

It does works in chrome (81) but crashes in firefox (76)

**Comment by imyelo** [comment]
Well, the reason can be confirmed that firefox does not support **Named capture groups** yet.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Browser_compatibility

**Comment by imyelo** [comment]
Hotfix v1.3.2 released.
