### ISSUE TITLE
更换样式

### ISSUE THREAD

**Issue by MistSeen** [imyelo/docsify-plantuml#2]
请问,我可以通过什么方式更换plantuml的样式?
或者使用默认样式. 
我觉得默认样式不错.

**Comment by imyelo** [comment]
当前版本只能另外在 UML 里用 [skinparams](http://plantuml.com/skinparam) 覆盖，很抱歉呢。

```
@startuml

skinparam shadowing true

autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```

**Comment by xnslong** [comment]
UML图的样式可不可以做成像其它插件一样，在index.html中通过参数来设定？因为大家喜欢的样式可能不一样，比如您觉得目前的默认配色好看，但我却更喜欢plantuml官方的默认配色，其它人可能还有其它口味。

**Comment by imyelo** [comment]
1.2.0 released. 支持配置参数使用传统风格：

https://github.com/imyelo/docsify-plantuml/blob/dbec9f3/README.md#skin
