### ISSUE TITLE
有可能提供样式切换功能吗

### ISSUE THREAD

**Issue by PandaraWen** [imyelo/docsify-plantuml#4]
自己是重度的 PlantUML 使用者，在 MWeb 以及语雀上面都重度依赖 PlantUML 画图，难得在 docsify-plantuml 上面发现有 PlantUML 的支持，很希望能够有使用默认样式的方法🙏🏻

**Comment by imyelo** [comment]
1.2.0 released. 支持配置参数使用传统风格：

https://github.com/imyelo/docsify-plantuml/blob/dbec9f3/README.md#skin

**Comment by imyelo** [comment]
move to #2
