### ISSUE TITLE
Local server responds with 404

### ISSUE THREAD

**Issue by asitemade4u** [imyelo/docsify-plantuml#8]
Hi,
Thank you for this plugin.
I am facing an issue however.
I have installed a docker-based server locally (https://hub.docker.com/r/plantuml/plantuml-server). It is accessible at `192.168.1.40:8789`.
I know it works well because I have connected VS Code to it.

Then, when I tried to connect from your plugin, after changing the settings in the docsify HTML file, as indicated in the doc, I get a `404`.
I tried different settings for `serverPath`, in vain:
- serverPath: 'http://192.168.1.40:8789/plantuml/png/'
- serverPath: 'http://192.168.1.40:8789'

Please help.
Best,
Stephen

**Comment by imyelo** [comment]
According to [plantuml-encoder](https://github.com/markushedvall/plantuml-encoder), it should be `serverPath: 'http://192.168.1.40:8789/plantuml/png/'`, but no idea why it doesn't work. Have you tried  `http://192.168.1.40:8789/plantuml/img/` or `http://192.168.1.40:8789/plantuml/svg/`?  🤔

**Comment by imyelo** [comment]
I tried the docker image (plantuml/plantuml-server) you mentioned and found that the `serverPath` in this case should be `http://192.168.1.40:8789/png/`. It works on my laptop.

**Comment by asitemade4u** [comment]
I confirm, it works! Maybe this should be added to the documentation to help other users (this docker PlantUML server is widely used).
Anyway, thanks a lot for the quick and relevant response!
